// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRZPVwg_FtU-vk7uzcSSigRF4zAM9sE7E',
    appId: '1:892070905244:web:19311783112c27d47bf459',
    messagingSenderId: '892070905244',
    projectId: 'auth-login-1b245',
    authDomain: 'auth-login-1b245.firebaseapp.com',
    storageBucket: 'auth-login-1b245.firebasestorage.app',
    measurementId: 'G-EVQQNL2ZBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKMzHgTbslIU-u1evkl5_AxlBMHjkXE90',
    appId: '1:892070905244:android:fb838a4c058d665e7bf459',
    messagingSenderId: '892070905244',
    projectId: 'auth-login-1b245',
    storageBucket: 'auth-login-1b245.firebasestorage.app',
  );

}